
service: sls-mongo

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  apiKeys:
    - richdev
  profile: devProfile
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB: ${self:custom.secrets.DB}

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: tabs # path will be domain.name.com/dev/tabs
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: tabs/{id} # path will be domain.name.com/dev/tabs/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/tabs
    events:
      - http:
          path: tabs
          method: get
          cors: true
  update:
    handler: handler.update # path will be domain.name.com/dev/tabs/1
    events:
      - http:
          path: tabs/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: tabs/{id} # path will be domain.name.com/dev/tabs/1
          method: delete
          cors: true


plugins:
  - serverless-offline
